classDiagram
    class Entity {
      -name : String
      -faction : String
      -rarity : String
      -card_type : String
      -card_subtype : String
      -spliced : Boolean
      -solbind : Boolean
      -abilities : Dictionary
      -ICollection : InterfaceCollection
      +__str__() String
    }

    class Deck {
      -name : String
      -forgeborn : Forgeborn
      -faction : String
      -cards : Dictionary
      -composition : Dictionary
      -seeks : Dictionary
      -provides : Dictionary
      -ICollection : InterfaceCollection
      +empty() Deck
      +populate()
      +get_rarities() List
      +get_composition() Dictionary
      +__add__(Deck) Deck
      +to_json() Dictionary
      +__eq__(Deck) Boolean
      +__str__() String
    }

    class Fusion {
      -name : String
      -fused : Deck
      -decks : List
      +decks_to_fusion(List) Deck
      +getDeck() Deck
    }

    class Forgeborn {
      -id : String
      -name : String
      -abilities : Dictionary
      -ICollection : InterfaceCollection
      +__str__() String
    }

    class Card {
      -entities : List
      -faction : String
      -provides : Dictionary
      -seeks : Dictionary
      -title : String
      -card_type : String
      -card_subtype : String
      -name : String
      -ICollection : InterfaceCollection
      +get_rarities() List
      +__str__() String
      +to_json() Dictionary
    }

    class UniversalCardLibrary {
      -entities : List
      -forgeborn : Dictionary
      +_read_forgeborn_from_csv(String) Dictionary
      +_read_entities_from_csv(String) List
      +search_entity(String, String) Entity
      +get_forgeborn(String) Forgeborn
      +load_decks_from_file(String) Tuple
      +load_data(String) List
      +load_decks_from_data(List) Tuple
      +load_fusions(List) Tuple
      +create_card_from_title(String, Dictionary) Card
      +__str__() String
    }

    Entity "1" -- "1" InterfaceCollection : contains
    Deck "1" -- "1" InterfaceCollection : contains
    Forgeborn "1" -- "1" InterfaceCollection : contains
    Card "1" -- "1" InterfaceCollection : contains

    Deck "1" -- "1" Forgeborn : contains
    Deck "1" -- "*" Entity : contains
    Fusion "1" -- "*" Deck : contains
    UniversalCardLibrary "1" -- "*" Entity : contains
    UniversalCardLibrary "1" -- "*" Forgeborn : contains
