name: SolDB-Conda
channels:  
  - conda-forge  
  - defaults  
dependencies:  
  - python=3.11  
  - ipywidgets=8.1.1  
  - pandas=2.2.0  
  - jupyterlab=4.1.0  
  - pandas-datareader  
  - matplotlib  
  - ipympl  
  - pymongo  
  - networkx  
  - numpy  
  - pillow  
  - scipy  
  - tqdm  
  - requests  
  - pip  
  - pip:  
    - pyvis # If pyvis is not available in conda channels  
    - jupyter-server-proxy # If jupyter-server-proxy is not available in conda channels  
    - qgridnext==2.0.0rc0 # If qgridnext is not available in conda channels  
    - icecream # If icecrls -eam is not available in conda channels  
    - tzlocal


